### ISSUE TITLE
for those who wants to try -- do not waste time because unsafeFlag is used in the package

### ISSUE THREAD

**Issue by izinin** [johnfairh/swift-steamworks#7]
The package product 'Steamworks' cannot be used as a dependency of this target because it uses unsafe build flags.

**Comment by johnfairh** [comment]
There are instructions [here](https://github.com/johnfairh/steamworks-swift?tab=readme-ov-file#how-to-use-this-project) on how to use the package.  Error messages about unsafe build flags mean that the Steam SDK isn't installed as expected.

If you can't get this working for some reason then all the normal ways of depending on packages with unsafe build flags should work.
